bucket_name   = "t2s-services-dev-bucket"
environment   = "dev"
active_environment = "blue"
index_file    = "../files/index-blue.html"
zone_id                 = "Z3EXAMPLE123"
record_name             = "t2s-services.com"
domain_name = "www.t2s-services.com"
cloudfront_domain_name  = "t2s-services.cloudfront.net"
cloudfront_hosted_zone_id = "Z2FDTNDATAQYW2"  # This is the default hosted zone ID for CloudFront
